<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Source/IngredientPlan.cs" Link="IngredientPlan.cs" />
    <Compile Include="../Source/SupplyTransfer.cs" Link="SupplyTransfer.cs" />
  </ItemGroup>
</Project>
